apriltag:
  ros__parameters:
    image_transport: raw
    publish_tfs: true
    family: 36h11
    size: 0.074
    max_hamming: 0
    detector:
      threads: 1
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
    tag:
      ids: [0]
      frames: [tag_0]
      sizes: [0.074]
