# Joint limits for Bimanual Setup (Balanced Mode)
joint_limits:
  franka1_fr3_joint1: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka1_fr3_joint2: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka1_fr3_joint3: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka1_fr3_joint4: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka1_fr3_joint5: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka1_fr3_joint6: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka1_fr3_joint7: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}

  franka2_fr3_joint1: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka2_fr3_joint2: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka2_fr3_joint3: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka2_fr3_joint4: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka2_fr3_joint5: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka2_fr3_joint6: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}
  franka2_fr3_joint7: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: true, max_acceleration: 2.0}

cartesian_limits:
  max_trans_vel: 0.5
  max_trans_acc: 1.0
  max_trans_dec: -1.0
  max_rot_vel: 1.0
