franka1_gripper:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
    goal_tolerance: 0.01
    max_effort: 50.0

franka2_gripper:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
    goal_tolerance: 0.01
    max_effort: 50.0
