# Goal (Richiesta al Server MTC)
string arm # e.g. 'left_arm', 'right_arm'
geometry_msgs/PoseStamped place_pose
float64 retreat_distance
---
# Result
bool success
string message
---
# Feedback
string status
float64 completion_percentage